# name: CI-CD Pipeline

# on:
#   push:
#     branches:
#       - main
#       - side

# jobs:
#   run-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test Step 1
#         run: echo "test is running"

#       - name: Test Step 2
#         run: echo "test successful"

#   deploy-app:
#     needs: run-test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy Step
#         run: echo "Deploying application......"



name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - side

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # 👈 clone repo

      - name: Test Step
        run: echo "test running"

  deploy-app:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4   # 👈 clone again

      - name: Deploy
        run: echo "deploying..."