name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step 1
        run: echo "test is running"

      - name: Test Step 2
        run: echo "test successful"

  deploy-app:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying application......"