name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - side

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls

      - name: Test Message
        run: echo "Test job completed"

  deploy:
    needs: test   # 👈 ensures deploy runs after test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Message
        run: echo "Deploy job running"