# # name : My First Workflow

# # on: [push,pull_request]

# # jobs:
  
# #   say-hello:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: print message
# #         run: echo "Hello, GitHub Action!"

# #       - name: print Names
# #         run: echo "Hello,Shiva this side! new reques in side1"

# #   say-bye:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: print message
# #         run: echo "Goodbye from second job Sir"


# name: CI-CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   run-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test Step 1
#         run: echo "test is running"

#       - name: Test Step 2
#         run: echo "test successful"

#   deploy-app:
#     needs: run-test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy Step
#         run: echo "Deploying application..."